# Generated by Django 3.0.8 on 2020-07-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-tourist_spot'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorite'},
        ),
        migrations.AlterModelOptions(
            name='touristspot',
            options={'ordering': ['-created'], 'verbose_name': 'TouristSpot', 'verbose_name_plural': 'TouristSpots'},
        ),
    ]
