# Generated by Django 3.0.8 on 2020-07-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200726_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-tourist_spot'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
    ]
